runtime: python
env: flex
runtime_config:
  python_version: 3
entrypoint: voila --port=$PORT --no-browser Farmlayers_Notebook.ipynb
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3